### Add basket item
POST {{host}}/api/v1/basket
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "00000000-0000-0000-0000-000000000001",
  "productName": "Camiseta básica",
  "size": "M",
  "color": "Negro",
  "unitPrice": 24.99,
  "quantity": 1
}
