<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.RabbitMQ.Client" />
        <PackageReference Include="Bogus" />
        <PackageReference Include="EFCore.NamingConventions" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="RabbitMQ.Client" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.Seq" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Carriers\Modules.Carriers.Features\Modules.Carriers.Features.csproj" />
      <ProjectReference Include="..\Catalog\Modules.Catalog.Features\Modules.Catalog.Features.csproj" />
      <ProjectReference Include="..\Common\Modules.Common.Infrastructure\Modules.Common.Infrastructure.csproj" />
      <ProjectReference Include="..\ModularMonolithTemplate.ServiceDefaults\Rpx.ServiceDefaults.csproj" />
      <ProjectReference Include="..\Shipments\Modules.Shipments.Features\Modules.Shipments.Features.csproj" />
      <ProjectReference Include="..\Stocks\Modules.Stocks.Features\Modules.Stocks.Features.csproj" />
      <ProjectReference Include="..\Users\Modules.Users.Features\Modules.Users.Features.csproj" />
      <ProjectReference Include="..\Basket\Modules.Basket.Features\Modules.Basket.Features.csproj" />
      <ProjectReference Include="..\Checkout\Modules.Checkout.Features\Modules.Checkout.Features.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="api_requests\Carriers\" />
      <Folder Include="api_requests\Stocks\" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>